/**
 * Canonical error codes returned by the API.
 * Every error response has the shape: { success: false, error: { code, message, details? } }
 */
const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  API_KEY_INVALID: 'API_KEY_INVALID',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Domain
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  CHAT_SESSION_NOT_FOUND: 'CHAT_SESSION_NOT_FOUND',
  UNSUPPORTED_COMMAND: 'UNSUPPORTED_COMMAND',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  STORAGE_ERROR: 'STORAGE_ERROR',
};

const HTTP_STATUS_BY_CODE = {
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.UNSUPPORTED_COMMAND]: 400,
  [ERROR_CODES.INVALID_FILE_TYPE]: 400,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.API_KEY_INVALID]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.JOB_NOT_FOUND]: 404,
  [ERROR_CODES.VIDEO_NOT_FOUND]: 404,
  [ERROR_CODES.WEBHOOK_NOT_FOUND]: 404,
  [ERROR_CODES.CHAT_SESSION_NOT_FOUND]: 404,
  [ERROR_CODES.EMAIL_TAKEN]: 409,
  [ERROR_CODES.PAYLOAD_TOO_LARGE]: 413,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.STORAGE_ERROR]: 502,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};

class ApiError extends Error {
  constructor(code, message, details) {
    super(message || code);
    this.name = 'ApiError';
    this.code = code;
    this.details = details;
    this.status = HTTP_STATUS_BY_CODE[code] || 500;
  }
}

module.exports = { ERROR_CODES, HTTP_STATUS_BY_CODE, ApiError };
